[package]
name = "clamn"
version = "0.1.0"
authors = ["Eashan Hatti <eashanhatti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8.0"
assoc_collections = { path = "../assoc_collections" }
macros = { path = "../macros" }
indoc = "1.0"