[package]
name = "clamn"
version = "0.1.0"
authors = ["Eashan Hatti <eashanhatti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
earlgrey = "0.3.0"
non-empty-collections = "0.1.9"
contracts = "0.6.0"